// AUTO-GENERATED from the live dukemocktrial.org roster pages.
// Maps each person (exact name) to their scraped photo in /public/team.
// Regenerate by re-running the team-photo scrape.
export const PHOTOS: Record<string, string> = {
  "A.G. Chancellor IV": "/team/a-g-chancellor-iv.jpeg",
  "Aarav Dagar": "/team/aarav-dagar.png",
  "Alex Park": "/team/alex-park.jpg",
  "Alexandria Thomas": "/team/alexandria-thomas.jpg",
  "Andrea Herman": "/team/andrea-herman.jpeg",
  "Andrew Legg": "/team/andrew-legg.jpg",
  "Ashley Martin": "/team/ashley-martin.png",
  "Avneesh Saravanapavan": "/team/avneesh-saravanapavan.jpeg",
  "Billy Silk": "/team/billy-silk.jpg",
  "Brigid Larkin": "/team/brigid-larkin.png",
  "Craig Vincent": "/team/craig-vincent.jpeg",
  "Emil Zakarian": "/team/emil-zakarian.jpeg",
  "Emma Kavcioglu": "/team/emma-kavcioglu.jpeg",
  "Eshaan Dhaliwal": "/team/eshaan-dhaliwal.jpg",
  "Evan Chan": "/team/evan-chan.png",
  "Georgia Lala": "/team/georgia-lala.jpg",
  "Haley Geers": "/team/haley-geers.jpg",
  "Heera Rajavel": "/team/heera-rajavel.png",
  "Irene Biju": "/team/irene-biju.png",
  "Isaac Toscano": "/team/isaac-toscano.jpg",
  "Jacob Hervey": "/team/jacob-hervey.png",
  "Jamie Dohopolski": "/team/jamie-dohopolski.jpg",
  "Javan Mayrand": "/team/javan-mayrand.jpeg",
  "Jeff Campbell": "/team/jeff-campbell.jpeg",
  "Jiahan Lyu": "/team/jiahan-lyu.jpg",
  "Jiewei Li": "/team/jiewei-li.png",
  "John Lee": "/team/john-lee.png",
  "Joshua Varon": "/team/joshua-varon.jpg",
  "Juliana Mayer": "/team/juliana-mayer.jpeg",
  "Kaleb Amare": "/team/kaleb-amare.jpeg",
  "Kari Tora": "/team/kari-tora.jpg",
  "Kate Westlake": "/team/kate-westlake.png",
  "Keith Buenrosto": "/team/keith-buenrosto.png",
  "Kyra Myers": "/team/kyra-myers.jpg",
  "Lauren Blake": "/team/lauren-blake.png",
  "Lena Nguyen": "/team/lena-nguyen.png",
  "Lilly Kelemen": "/team/lilly-kelemen.jpeg",
  "Madeline Matthys": "/team/madeline-matthys.png",
  "Matthew Webber": "/team/matthew-webber.jpeg",
  "Maya Arora": "/team/maya-arora.png",
  "Milton Padilla, Jr.": "/team/milton-padilla-jr.png",
  "Minjee Kim": "/team/minjee-kim.jpg",
  "Nellie Sun": "/team/nellie-sun.jpeg",
  "Nhu Bui": "/team/nhu-bui.png",
  "Paul Kim": "/team/paul-kim.jpeg",
  "Ram Asaithambi": "/team/ram-asaithambi.jpg",
  "Rebecca Blair": "/team/rebecca-blair.png",
  "Riya Dange": "/team/riya-dange.jpg",
  "Sara Grippo": "/team/sara-grippo.jpg",
  "Seva Castleberry": "/team/seva-castleberry.jpeg",
  "Sonali Mehta": "/team/sonali-mehta.jpg",
  "Sophie Brynes": "/team/sophie-brynes.png",
  "Timothy Kreinberg": "/team/timothy-kreinberg.jpg",
  "Tori Ely": "/team/tori-ely.png",
  "Travis Swafford": "/team/travis-swafford.jpg",
  "Tristan Malhotra": "/team/tristan-malhotra.jpg",
  "William Feng": "/team/william-feng.png",
  "Zek Zhang": "/team/zek-zhang.jpeg",
};
